site_name: anyuri
site_description: Polymorphic URI types for Python
strict: true
site_url: https://lucemia.github.io/anyuri/

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs

repo_name: lucemia/anyuri
repo_url: https://github.com/lucemia/anyuri
edit_uri: edit/main/docs/

validation:
  omitted_files: ignore
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Get Started:
      - Welcome: index.md
  - Comparison: comparison.md
  - API Documentation:
      - AnyUri: api/anyuri.md
      - Providers: api/providers.md
      - I/O (download & upload): api/io.md
      - Exceptions: api/exceptions.md
      - Utils: api/utils.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true

watch:
  - src
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - griffe_inherited_docstrings
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            docstring_style: google
            docstring_section_style: table
            show_root_heading: true
